// NOTE: This file can be regenerated by Uniwind in consumer apps when custom themes are enabled.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
  export interface UniwindConfig {
    themes: readonly ['light', 'dark'];
  }
}

export {};
