import { NextRequest, NextResponse } from "next/server";
import { assertPublicHttpUrl, BlockedUrlError, safeFetch } from "../_ssrf-guard";

interface UrlWithDepth {
  url: string;
  depth: number;
}

const CONCURRENCY = 10;
const PER_PAGE_TIMEOUT = 30000;
const OVERALL_TIMEOUT = 180000; // 180s hard limit

async function fetchAndParseLinks(url: string, baseOrigin: string): Promise<string[]> {
  try {
    const res = await safeFetch(url, {
      headers: {
        "User-Agent": "Mozilla/5.0 (compatible; NayanUI-SitemapBot/1.0; +https://nayanui.com)",
        Accept: "text/html",
      },
      signal: AbortSignal.timeout(PER_PAGE_TIMEOUT),
    });

    if (!res.ok) return [];
    const contentType = res.headers.get("content-type") || "";
    if (!contentType.includes("text/html")) return [];

    const html = await res.text();
    const links: string[] = [];

    const regex = /<a\s+[^>]*href=["']([^"'#]*?)["'][^>]*>/gi;
    let m;
    while ((m = regex.exec(html)) !== null) {
      const href = m[1].trim();
      if (!href || href.startsWith("javascript:") || href.startsWith("mailto:") || href.startsWith("tel:")) continue;

      try {
        const parsed = new URL(href, url);
        if (parsed.origin !== baseOrigin) continue;
        parsed.hash = "";
        links.push(parsed.href);
      } catch {
        // invalid URL, skip
      }
    }

    return links;
  } catch {
    return [];
  }
}

function buildSitemapXml(
  urls: UrlWithDepth[],
  maxDepth: number,
  changefreq: string,
): string {
  let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
  xml += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n`;
  xml += `        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n`;
  xml += `        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9\n`;
  xml += `        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">\n`;
  xml += `  <!-- Generated by Nayan UI Sitemap Generator - https://www.nayanui.com/tools/sitemap-generator -->\n`;

  const depthMax = Math.max(maxDepth, 1);
  for (const { url, depth } of urls) {
    const priority = Math.max(0.1, (depthMax - depth) / depthMax);
    xml += `  <url>\n`;
    xml += `    <loc>${escapeXml(url)}</loc>\n`;
    xml += `    <changefreq>${changefreq}</changefreq>\n`;
    xml += `    <priority>${priority.toFixed(1)}</priority>\n`;
    xml += `  </url>\n`;
  }

  xml += `</urlset>\n`;
  return xml;
}

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { website, depth: maxDepth = 10, changefreq = "daily", maxUrls = 5000 } = body;

    if (!website || typeof website !== "string") {
      return NextResponse.json({ error: "Website URL is required" }, { status: 400 });
    }

    let baseUrl = website.trim();
    if (!/^https?:\/\//i.test(baseUrl)) baseUrl = "https://" + baseUrl;
    const parsedBase = await assertPublicHttpUrl(baseUrl);
    const baseOrigin = parsedBase.origin;
    if (parsedBase.pathname === "/") baseUrl = baseOrigin + "/";

    const visited = new Set<string>();
    const queue: UrlWithDepth[] = [{ url: baseUrl, depth: 0 }];
    visited.add(baseUrl);

    const cap = Math.min(Math.max(maxUrls, 1), 10000);
    const deadline = Date.now() + OVERALL_TIMEOUT;

    // BFS with concurrency
    while (queue.length > 0 && visited.size < cap && Date.now() < deadline) {
      // Take up to CONCURRENCY items from the queue
      const batch: UrlWithDepth[] = [];
      while (batch.length < CONCURRENCY && queue.length > 0) {
        batch.push(queue.shift()!);
      }

      // Fetch all pages in the batch concurrently
      const results = await Promise.all(
        batch.map(async ({ url, depth }) => {
          if (depth >= maxDepth) return [];
          return (await fetchAndParseLinks(url, baseOrigin)).map((link) => ({
            link,
            depth: depth + 1,
          }));
        }),
      );

      // Collect new links
      for (const links of results) {
        for (const { link, depth } of links) {
          if (!visited.has(link) && visited.size < cap) {
            visited.add(link);
            queue.push({ url: link, depth });
          }
        }
      }
    }

    const urlsWithDepth: UrlWithDepth[] = Array.from(visited).map((url) => {
      const pathSegments = new URL(url).pathname.split("/").filter(Boolean).length;
      return { url, depth: pathSegments };
    });

    urlsWithDepth.sort((a, b) => a.depth - b.depth || a.url.localeCompare(b.url));

    const xml = buildSitemapXml(urlsWithDepth, Math.max(maxDepth, 1), changefreq);

    return NextResponse.json({
      xml,
      urlCount: urlsWithDepth.length,
      urls: urlsWithDepth.map((u) => u.url),
    });
  } catch (err: any) {
    if (err instanceof BlockedUrlError) {
      return NextResponse.json({ error: err.message }, { status: 400 });
    }
    return NextResponse.json({ error: err.message || "Crawl failed" }, { status: 500 });
  }
}
