name: Pull Request
description: Submit a pull request
title: "[PR]: "
body:
  - type: checkboxes
    attributes:
      label: "Package"
      description: Select the package this PR is related to
      options:
        - label: Nayan UI CLI
        - label: Nayan UI Games
        - label: Nayan UI Website
        - label: Nayan UI React JS
        - label: Nayan UI React Native
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the changes
  - type: checkboxes
    attributes:
      label: "Type of Change"
      options:
        - label: Bug fix
        - label: New feature
        - label: Documentation update
  - type: checkboxes
    attributes:
      label: "Checklist"
      options:
        - label: I have tested the code and confirmed it works as expected.
        - label: I have added necessary documentation (if applicable).
        - label: My changes follow the code style and guidelines of this project.
