name: Publish website docker images
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Docker Authentication
        run: |
          docker login -u ursnj -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build & Publish Nayan UI Website Image
        run: |
          docker build -f packages/website/Dockerfile -t ursnj/nayanui:latest .
          docker push ursnj/nayanui:latest
