name: Publish website docker images
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Authentication
        uses: docker/login-action@v3
        with:
          username: ursnj
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Publish Nayan UI Website Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: packages/website/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ursnj/nayanui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
