name: Publish nayan (cli) package to npm
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: corepack enable
        working-directory: .

      - name: Install dependencies
        run: yarn install
        working-directory: .

      - name: Build nayan (cli) package
        run: yarn build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org/
